controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    # Wheel
    steering_controller:
      type: position_controllers/JointGroupPositionController

    wheel_controller:
      type: velocity_controllers/JointGroupVelocityController

    # Gripper
    right_gripper_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    left_gripper_controller:
      type: joint_trajectory_controller/JointTrajectoryController

# Position Controllers ---------------------------------------
steering_controller:
  ros__parameters:
    joints:
      - front_right_steering_joint
      - front_left_steering_joint
      - rear_left_steering_joint
      - rear_right_steering_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

# Velocity Controllers ---------------------------------------
wheel_controller:
  ros__parameters:
    joints:
      - front_right_dir_wheel_joint
      - front_left_dir_wheel_joint
      - rear_left_dir_wheel_joint
      - rear_right_dir_wheel_joint
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity
