<?xml version="1.0"?>
<robot name="abu_bot" xmlns:xacro="http://ros.org/wiki/xacro">
    <!-- ROBOT -->
    <xacro:include filename="$(find abu_description)/urdf/base.urdf.xacro" />
    <xacro:include filename="$(find abu_description)/urdf/properties.urdf.xacro" />
    <xacro:include filename="$(find abu_description)/urdf/sensors/imu.urdf.xacro" />
    <xacro:include filename="$(find abu_description)/urdf/robot_control.urdf.xacro" />
    <xacro:include filename="$(find abu_description)/urdf/sensors/depth_sensor.urdf.xacro" />
    <xacro:include filename="$(find abu_description)/urdf/sensors/generic_laser.urdf.xacro" />


    <xacro:base 
        length="${base_length}" 
        width="${base_width}" 
        height="${base_height}" 
        mass="${base_mass}"
        wheel_radius="${wheel_dir_radius}"
        wheel_pos_z="${wheel_pos_z}"
    />

    <xacro:imu/>

    <xacro:generic_laser>
        <xacro:insert_block name="laser_pose" />
    </xacro:generic_laser>
    
    <xacro:depth_sensor>
        <xacro:insert_block name="depth_sensor_pose" />
    </xacro:depth_sensor>

    <xacro:robot_controller/> 

    <!-- DRIVE -->
    <xacro:include filename="$(find abu_description)/urdf/drive.urdf.xacro" />
    <xacro:include filename="$(find abu_description)/urdf/swerve_wheel/wheel.urdf.xacro" />
    <xacro:include filename="$(find abu_description)/urdf/swerve_wheel/wheel.transmission.xacro" />
    <xacro:include filename="$(find abu_description)/urdf/swerve_wheel/steering.transmission.xacro" />

    <!-- <xacro:swerve_wheel 
        side="front_left"
        rot_radius="${wheel_rot_radius}" 
        rot_width="${wheel_rot_width}" 
        dir_radius="${wheel_dir_radius}" 
        dir_width="${wheel_dir_width}" 
        pos_x="${wheel_pos_x}" 
        pos_y="${wheel_pos_y}" 
        pos_z="${wheel_pos_z}"
        dir_pos_z="${wheel_dir_pos_z}" 
        mass="${wheel_mass}"
    />

    <xacro:swerve_wheel 
        side="front_right"
        rot_radius="${wheel_rot_radius}" 
        rot_width="${wheel_rot_width}" 
        dir_radius="${wheel_dir_radius}" 
        dir_width="${wheel_dir_width}" 
        pos_x="${wheel_pos_x}" 
        pos_y="${-wheel_pos_y}" 
        pos_z="${wheel_pos_z}" 
        dir_pos_z="${wheel_dir_pos_z}" 
        mass="${wheel_mass}"
    />
    <xacro:swerve_wheel 
        side="rear_left"
        rot_radius="${wheel_rot_radius}" 
        rot_width="${wheel_rot_width}" 
        dir_radius="${wheel_dir_radius}" 
        dir_width="${wheel_dir_width}" 
        pos_x="${-wheel_pos_x}" 
        pos_y="${wheel_pos_y}" 
        pos_z="${wheel_pos_z}" 
        dir_pos_z="${wheel_dir_pos_z}" 
        mass="${wheel_mass}"
    />

    <xacro:swerve_wheel 
        side="rear_right"
        rot_radius="${wheel_rot_radius}" 
        rot_width="${wheel_rot_width}" 
        dir_radius="${wheel_dir_radius}" 
        dir_width="${wheel_dir_width}" 
        pos_x="${-wheel_pos_x}" 
        pos_y="${-wheel_pos_y}" 
        pos_z="${wheel_pos_z}" 
        dir_pos_z="${wheel_dir_pos_z}" 
        mass="${wheel_mass}"
    /> -->

    <!-- <ros2_control name="swerve_robot_gazebo_system" type="system">
        <hardware>
            <plugin>gazebo_ros2_control/GazeboSystem</plugin>
        </hardware>
        <xacro:wheel_transmission side="front_right" />
        <xacro:wheel_transmission side="front_left" />
        <xacro:wheel_transmission side="rear_left" />
        <xacro:wheel_transmission side="rear_right" />
        <xacro:steer_transmission side="front_right" />
        <xacro:steer_transmission side="front_left" />
        <xacro:steer_transmission side="rear_left" />
        <xacro:steer_transmission side="rear_right" />
    </ros2_control>

    <xacro:drive_controller/>  -->

    <!-- TELESCOPE -->
    <xacro:include filename="$(find abu_description)/urdf/telescope/silder_1.urdf.xacro" />
    <xacro:include filename="$(find abu_description)/urdf/telescope/silder_2.urdf.xacro" />
    <xacro:include filename="$(find abu_description)/urdf/telescope/silder_wrist.urdf.xacro" />
    <xacro:include filename="$(find abu_description)/urdf/telescope/tele_hand.urdf.xacro" />

    <xacro:silder_1
    length="${silder_1_length}"
    width="${silder_1_width}"
    height="${silder_1_height}"
    pos_x="${silder_1_pos_x}"
    pos_y="${silder_1_pos_y}"
    pos_z="${silder_1_pos_z}"
    mass="${silder_1_mass}"
    />
    <xacro:silder_2
    length="${silder_2_length}"
    width="${silder_2_width}"
    height="${silder_2_height}"
    pos_x="${silder_2_pos_x}"
    pos_y="${silder_2_pos_y}"
    pos_z="${silder_2_pos_z}"
    mass="${silder_2_mass}"
    />
    <xacro:silder_wrist
    length="${silder_wrist_length}"
    width="${silder_wrist_width}"
    height="${silder_wrist_height}"
    pos_x="${silder_wrist_pos_x}"
    pos_y="${silder_wrist_pos_y}"
    pos_z="${silder_wrist_pos_z}"
    mass="${silder_wrist_mass}"
    />
    <xacro:tele_hand
    side="right"
    length="${silder_hand_length}"
    width="${silder_hand_width}"
    height="${silder_hand_height}"
    pos_x="${silder_hand_pos_x}"
    pos_y="${silder_hand_pos_y}"
    pos_z="${silder_hand_pos_z}"
    mass="${silder_hand_mass}"
    />
    <xacro:tele_hand
    side="left"
    length="${silder_hand_length}"
    width="${silder_hand_width}"
    height="${silder_hand_height}"
    pos_x="${silder_hand_pos_x - 0.004}"
    pos_y="${-silder_hand_pos_y}"
    pos_z="${silder_hand_pos_z}"
    mass="${silder_hand_mass}"
    />



</robot>