scan_to_scan_filter_chain:
  ros__parameters:
    filter1:
      name: angle
      type: laser_filters/LaserScanAngularBoundsFilter
      params:
        lower_angle: -1.29
        upper_angle: 1.29

sllidar_node:
  ros__parameters:
    serial_port: /dev/ttyUSB0
    inverted: True # Blue True Red False
    frame_id: laser

scan_filter_node:
  ros__parameters:
    min_angle: -1.25
    max_angle: 1.25
